Refactor hard-coded arguments
upenn-cis5520/final-project_Vopaaz_zhlian1997 pull request #14
Opened 2022-12-08 19:50 UTC by zhlian1997

- added command line options: fps, sampled
- refactored to read dynamic terminal size
- more accurate thread delay to achieve more 'uniform' video playing speed

2022-12-08 22:04 UTC, Vopaaz requested changes

2022-12-08 22:04 UTC, Vopaaz commented on src/UI.hs
> +    threadDelay $ timeDiff * 1000 -- TODO: refactor delay
In my testing, the display speed doesn't reflect the fps argument. Maybe it's here? that the delay should be computed based on fps?

2022-12-08 22:47 UTC, zhlian1997 commented on src/UI.hs
> +    threadDelay $ timeDiff * 1000 -- TODO: refactor delay
Fps argument does not affect display speed now because of line 113. I set baseline interval fixed at 200ms now, instead of being determined by fps. If you uncomment line 112 and you can see fps taking effect.

2022-12-08 22:50 UTC, zhlian1997 commented on src/UI.hs
> +    threadDelay $ timeDiff * 1000 -- TODO: refactor delay
Fps is kinda tricky here: if I set fps=2, the amount of images generated is reasonable but the playing speed is too slow. When fps=5, the playing speed looks good but there are way too many images. That's why I only let the fps argument to affect the video splitting stage for now.

2022-12-08 22:53 UTC, zhlian1997 commented on app/Main.hs
> +    - (optional) sampled: --sampled / -s to turn on sampled sizing,
This argument can be easily refactored from boolean to integer enumeration when we introduce more resizing strategies.

2022-12-09 04:36 UTC, zhlian1997 commented on src/UI.hs
> +    threadDelay $ timeDiff * 1000 -- TODO: refactor delay
Sure. Now the ascii vid speed should be the same as the original video.

2022-12-09 04:37 UTC, merged