Introduce colored ascii
upenn-cis5520/final-project_Vopaaz_zhlian1997 pull request #19
Opened 2022-12-15 06:21 UTC by zhlian1997

Introduced 8-color ascii printing feature. 
- Added new command line option: --colored/-c 
- Added a new data type (Ascii) in ImageToAscii module, which includes both character / its color. By introducing the datatype, we can use the same set of functions to process both plain ascii and colored ascii. As a result, multiple interfaces in ImageToAscii have to be changed
- Refactored UI/Main module to enable colored ascii
- Fixed some broken tests caused by changed interfaces in ImageToAscii 

TODOs:
- Add colored ascii related tests
- Add tests for ArgParser
- Fix some unsafe function calls (!!, head, etc.)

2022-12-15 19:25 UTC, Vopaaz requested changes
# Please don't merge this as of now

On my end, this version is lagging a lot, even for non-colored version, using the Sample method. The current main version can smoothly play at ~10 fps, but this version is like 1 fps.

Apart from my code style suggestions, we also need to investigate in the performance issue.

2022-12-15 19:25 UTC, Vopaaz commented on src/ImageToAscii.hs
> +imageToAsciiByTerminalInfo img colored nRows nCols hChar wChar =
If we place `colored` and `ResizeStrategy` near each other, it looks more consistent

2022-12-15 19:25 UTC, Vopaaz commented on src/ImageToAscii.hs
> +imageToAsciiByRowColNumber img colored nRows nCols s = resizedImageToAscii (resizeImage img nRows nCols s) colored
Similar `colored` position move for all these functions

2022-12-15 19:25 UTC, Vopaaz commented on test/ImageToAsciiTest.hs
> +  let ascii = imageToAsciiByTerminalInfo img False nRows nCols hChar wChar s
If you just add another boolean argument to the `prop_` function (instead of hardcoding `False`, and pass it along, it should also work

2022-12-15 19:25 UTC, Vopaaz commented on test/ImageToAsciiTest.hs
> +  let ascii = imageToAsciiByRowColNumber img False h w s
Similar for all the `False`'s in the other tests

2022-12-15 19:25 UTC, Vopaaz commented on test/ImageToAsciiTest.hs
> +    [ rgbToChar (0, 0, 0) False ~?= ' ',
We can add some tests for `True`

2022-12-15 20:11 UTC, zhlian1997 commented on src/ImageToAscii.hs
> +imageToAsciiByTerminalInfo img colored nRows nCols hChar wChar =
Makes sense. I place them together now.

2022-12-15 20:12 UTC, zhlian1997 commented on test/ImageToAsciiTest.hs
> +  let ascii = imageToAsciiByRowColNumber img False h w s
done

2022-12-16 02:38 UTC, Vopaaz commented
Adopted to the `color-optim` branch, which will be refactored and PR later

2022-12-16 02:38 UTC, closed without merging